name: Generate Pacman GitHub Activity

on:
  schedule: # Roda automaticamente todos os dias à meia-noite
    - cron: "0 0 * * *"
  workflow_dispatch: # Permite que você rode manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Pacman Animation
        uses: jasonlong/github-readme-pacman@main
        with:
          github_user_name: developertiagosilva
          output: dist/pacman.svg

      - name: Deploy to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: pacman-output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}